---USUARIO ADMIN
---CASO 1: ESTRATEGIA DE USUARIOS

--CREACION DE USUARIO PRY2205_USER1
CREATE USER PRY2205_USER1
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE USER TO PRY2205_USER1;
GRANT CREATE PROFILE TO PRY2205_USER1;
GRANT CREATE TABLE TO PRY2205_USER1;
GRANT CREATE VIEW TO PRY2205_USER1;
GRANT CREATE INDEX TO PRY2205_USER1;
GRANT CREATE SYNONYM TO PRY2205_USER1;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_USER1;

--CREACION DE USUARIO PRY2205_USER2
CREATE USER PRY2205_USER2
IDENTIFIED BY "PRY2205.semana_8"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER2;
GRANT CREATE VIEW TO PRY2205_USER2;
GRANT CREATE USER TO PRY2205_USER2;
GRANT CREATE PROFILE TO PRY2205_USER2;

GRANT SELECT ON PRY2205_USER1.PAGOS TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.BONO_CONSULTA TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.SISTEMA_SALUD TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.SALUD TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.PACIENTE TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.MEDICO TO PRY2205_USER2;
GRANT SELECT ON PRY2205_USER1.CARGO TO PRY2205_USER2;

--CREACIÓIN DEL ROLES
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P;

--ASIGNACIÓN DE PRIVILEGIOS
GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;

-- CASO 2 PRY2205_USER1
-- CREACION DE SINONIMOS PUBLICOS PARA SER USADOS POR OTROS USUARIOS
CREATE PUBLIC SYNONYM syn_pgs FOR PRY2205_USER1.pagos;
CREATE PUBLIC SYNONYM syn_pac FOR PRY2205_USER1.paciente;
CREATE PUBLIC SYNONYM syn_dem FOR PRY2205_USER1.DET_ESPECIALIDAD_MED;
CREATE PUBLIC SYNONYM syn_em FOR PRY2205_USER1.ESPECIALIDAD_MEDICA;
CREATE PUBLIC SYNONYM syn_bc FOR PRY2205_USER1.BONO_CONSULTA;
CREATE PUBLIC SYNONYM syn_ss FOR PRY2205_USER1.SISTEMA_SALUD;
CREATE PUBLIC SYNONYM syn_med FOR PRY2205_USER1.MEDICO;
CREATE PUBLIC SYNONYM syn_uc FOR PRY2205_USER1.UNIDAD_CONSULTA;
CREATE PUBLIC SYNONYM syn_crg FOR PRY2205_USER1.CARGO;
CREATE PUBLIC SYNONYM syn_sld FOR PRY2205_USER1.SALUD;
CREATE PUBLIC SYNONYM syn_dcto FOR PRY2205_USER1.PCT_DESCTO_ADULTO_MAYOR;
CREATE PUBLIC SYNONYM syn_cbpa FOR PRY2205_USER1.CANT_BONOS_PACIENTES_ANNIO;

-- CASO 2 PRY2205_USER2
-- CREACION DE VISTA: VW_RECALCULO_COSTOS
CREATE OR REPLACE VIEW VW_RECALCULO_COSTOS AS
SELECT
    LPAD(REPLACE(TO_CHAR(pac.pac_run,'99,999,999'),',','.'),15) || '-' || pac.dv_run AS RUT_PACIENTE,
    UPPER(pac.apaterno || ' ' || pac.amaterno || ' ' || pac.pnombre) AS NOMBRE_PACIENTE,
    NVL(INITCAP(sld.descripcion),'Sin sistema de salud') AS SISTEMA_SALUD,
    LPAD(REPLACE(TO_CHAR(bc.costo, '$99,999'),',','.'),25) AS COSTO,
    bc.hr_consulta AS HORARIO_ATENCION,
    TO_CHAR(bc.fecha_bono, 'DD/MM/YY') AS FECHA_CONSULTA,
    
    CASE 
        WHEN bc.costo BETWEEN 15000 AND 25000 THEN ROUND(bc.costo * 1.15)
        WHEN bc.costo > 25000 THEN ROUND(bc.costo * 1.20)
        ELSE bc.costo
    END AS REAJUSTE

FROM syn_bc bc
JOIN syn_pac pac
    ON pac.pac_run = bc.pac_run
JOIN syn_sld sld
    ON pac.sal_id = sld.tipo_sal_id
    
WHERE EXTRACT(YEAR FROM bc.fecha_bono) = EXTRACT(YEAR FROM SYSDATE) - 1
AND TO_DATE(bc.hr_consulta, 'HH24:MI') > TO_DATE ('17:15', 'HH24:MI')
AND sld.sal_id IN (
                   SELECT sal_id
                   FROM syn_sld
                   WHERE sal_id BETWEEN 10 AND 40 ---PARA FONASA
                   OR sal_id BETWEEN 50 AND 100 ---PARA ISAPRE
);

SELECT * FROM VW_RECALCULO_COSTOS
ORDER BY FECHA_CONSULTA DESC, RUT_PACIENTE ASC;

GRANT SELECT ON PRY2205_USER2.VW_RECALCULO_COSTOS TO PRY2205_USER1;
drop view VW_RECALCULO_COSTOS;

---CASO 3 PRY2205_USER1 (OWNER)
---CREACION DE VISTA: VW_AUM_MEDICO_X_CARGO

CREATE OR REPLACE VIEW VW_AUM_MEDICO_X_CARGO AS
SELECT
    LPAD(REPLACE(TO_CHAR(m.rut_med,'09,999,999'),',','.'),15) || '-' || m.dv_run AS RUT_MEDICO,
    c.nombre AS CARGO,
    LPAD(REPLACE(TO_CHAR(NVL(m.sueldo_base,0),'99,999,999'),',','.'),20) AS SUELDO_ACTUAL,
    LPAD(REPLACE(TO_CHAR(ROUND(NVL(m.sueldo_base,0) * 1.15),'99,999,999'),',','.'),20) AS SUELDO_AUMENTADO

FROM syn_med m
JOIN syn_crg c
    ON m.car_id = c.car_id

WHERE UPPER(c.nombre) LIKE '%ATENCIÓN%';

CREATE INDEX IDX_CARGO_UPPER_DESC
ON syn_cargo (UPPER(descripcion));

SELECT * FROM VW_AUM_MEDICO_X_CARGO
ORDER BY SUELDO_AUMENTADO DESC;

GRANT SELECT ON PRY2205_USER1.VW_AUM_MEDICO_X_CARGO TO PRY2205_USER2;